### ISSUE TITLE
Why is there no ionosphere topic?

### ISSUE THREAD

**Issue by JiangZhengok** [HKUST-Aerial-Robotics/ublox_driver#1]
Today, I use this ublox_driver to collect data. The collected rosbag info as follows: 

![image](https://user-images.githubusercontent.com/34699594/119771016-97501080-beef-11eb-837b-b975ed99a524.png)

Obviously, we drove for 21 minutes, but there is no /ublox_driver/iono_params topic. But your rosbag has /ublox_driver/iono_params topic. 
I know from your ublox_driver code( as follows) that both the ephemeris and the ionosphere are parsed from the RXM-SFRBX. 

![image](https://user-images.githubusercontent.com/34699594/119773759-b355b100-bef3-11eb-9f93-9eb5782a4deb.png)

So I don't understand why there's ephemeris but there's no ionosphere. Is it something to do with the environment or the weather? Today's weather is cloudy, we collected data in the urban open environment. Or, could it have something to do with a GPS antenna?

**Comment by shaozu** [comment]
The code only parses ionospheric parameters from Beidou's ephemeris data, so make sure that your receiver supports Beidou and it's enabled. Nevertheless, the ionospheric parameters can be obtained offline so your bag is still good to use.

**Comment by JiangZhengok** [comment]
> The code only parses ionospheric parameters from Beidou's ephemeris data, so make sure that your receiver supports Beidou and it's enabled. Nevertheless, the ionospheric parameters can be obtained offline so your bag is still good to use.

I see. I banned Beidou yesterday by u-center. Thank you very much. 
Do ionospheric parameters fluctuate very little in the same region at the same time? 
In the same area at different times?
How to get ionospheric parameters offline? 
Do you get the the default ionospheric parameters of visensor_left_f9p_config.yaml offline?

**Comment by shaozu** [comment]
The ionospheric parameters vary from time to time, but I think the difference of the final ionospheric delay can be small.

You can obtain these parameters from [here](https://cddis.nasa.gov/Data_and_Derived_Products/GNSS/broadcast_ephemeris_data.html). Simply download the ephemeris file and the parameters are included inside.

The default parameters in `visensor_left_f9p_config.yaml` are drawn from a random day. It doesn't matter whether is comes from online or offline. The values are just the same.

**Comment by JiangZhengok** [comment]
Hi, @shaozu. Thanks for your help. I recollected the data today. Does GVINS have data frequency requirements? In my bag, image is 10Hz, Imu is 100Hz. The system always restarts after GNSS-VI align when I run GVINS use my bag. I use my config file. Always print that "throw gnss, only should happen at the beginning" during the run. Is it because I didn't do hardware synchronization?
![image](https://user-images.githubusercontent.com/34699594/120193963-9e5c8300-c24f-11eb-8f1f-d8aceadcc9ae.png)

It can run 300m before the trajectory divergence if I disable GNSS.
![image](https://user-images.githubusercontent.com/34699594/120193806-68b79a00-c24f-11eb-8fca-9a57f71579e2.png)

**Comment by shaozu** [comment]
Hi, @JiangZhengok. What's the frequency of your GNSS measurement?

If the message "throw gnss, only should happen at the beginning" pops up frequently, then synchronization may be an issue.

**Comment by JiangZhengok** [comment]
> Hi, @JiangZhengok. What's the frequency of your GNSS measurement?
> 
> If the message "throw gnss, only should happen at the beginning" pops up frequently, then synchronization may be an issue.

The frequency of my GNSS measurement is 20Hz that is the same as yours. Hardware synchronization cannot be achieved in our car at this time. I'm looking for other solutions. Do you have any good suggestions? I'm now adding the wheel speed constraint.

**Comment by shaozu** [comment]
The frequency of GNSS in our platform is 10Hz (camera: 20Hz, IMU: 200Hz). During the process we halve the image's frequency to improve efficiency as well as match with that of GNSS. So in you case, you may set the GNSS output to 10Hz and modify the code [here](https://github.com/HKUST-Aerial-Robotics/GVINS/blob/844530b45f8832df5b4c8036cb0aefdc1bbeed81/estimator/src/estimator_node.cpp#L255).

**Comment by JiangZhengok** [comment]
> The frequency of GNSS in our platform is 10Hz (camera: 20Hz, IMU: 200Hz). During the process we halve the image's frequency to improve efficiency as well as match with that of GNSS. So in you case, you may set the GNSS output to 10Hz and modify the code [here](https://github.com/HKUST-Aerial-Robotics/GVINS/blob/844530b45f8832df5b4c8036cb0aefdc1bbeed81/estimator/src/estimator_node.cpp#L255).

Sorry, I made a mistake yesterday. My GNSS observation frequency is 10Hz. I've changed the code which halve the image's frequency and the message that “throw gnss, only should happen at the beginning” doesn't pop up frequently. I note that your body frame is x-y-z(right-down-front), but my body frame is x-y-z(right-front-up). Does that affect the result? Do I need to change the code?

**Comment by shaozu** [comment]
The orientation of the body(IMU) frame does not matter. It only affect the extrinsic parameters between camera and IMU.
