### ISSUE TITLE
The echoed six messages updates slowly.

### ISSUE THREAD

**Issue by SSZ1** [HKUST-Aerial-Robotics/ublox_driver#10]
I ran the Ublox-Driver using the H-RTK-F9P and picked up the 6 messages. But some of them updated slowly when I echoed them like the ublox_deiver/ephem ,  ublox_deiver/glo_ephem. But the others are normal. Why is this?    Is something wrong with the device or the project?

**Comment by shaozu** [comment]
Hi, @SSZ1. This is totally normal as GNSS data works this way. It takes time for the receiver to download the ephemeris data from the satellite via the very weak link.
