### ISSUE TITLE
The terminal window shows "length error " And the message updates slowly when I echo.

### ISSUE THREAD

**Issue by SSZ1** [HKUST-Aerial-Robotics/ublox_driver#11]
I ran the Ublox-Driver using the H-RTK-F9P and picked up the 6 messages. But it shows a "length error" in the Ublox-driver terminal window. Some of the messages updated slowly when I echoed them like the ublox_deiver/ephem , ublox_deiver/glo_ephem. But the others are normal. Why is this? Is something wrong with the device or the project? Or is the GNSS signal weak? Could you offer some advice, please?

![image](https://user-images.githubusercontent.com/36888758/197674532-e2f03077-b42a-44e1-b78a-8973e085d701.png)

Thanks for your attention.

**Comment by Buttosaii** [comment]
Hi @SSZ1, I am facing this error message and slow output results too. For me, its seems that range_meas have the fastest update rate and time_pulse_info have the slowest (barely ever received any results). Is there any update on this issue for you?

I am currently using U-blox ZED F9P on Ubuntu 18.04 Melodic.

**Comment by SSZ1** [comment]
> Hi @SSZ1, I am facing this error message and slow output results too. For me, its seems that range_meas have the fastest update rate and time_pulse_info have the slowest (barely ever received any results). Is there any update on this issue for you?
> 
> I am currently using U-blox ZED F9P on Ubuntu 18.04 Melodic.

It's OK that there is this issue. The GNSS board of my device is the same as yours. And it turns out that this situation won't influence the following experiments.  It's OK to use the messages from the Ublox driver.

**Comment by Buttosaii** [comment]
That is great to hear! Is your ublox_deiver/ephem and ublox_deiver/glo_ephem topics still facing slow update rate?

**Comment by SSZ1** [comment]
> That is great to hear! Is your ublox_deiver/ephem and ublox_deiver/glo_ephem topics still facing slow update rate?

Yes. The ephem data always updates slowly.
