### ISSUE TITLE
Cannot load message class for [gnss_comm/GnssPVTSolnMsg]

### ISSUE THREAD

**Issue by slender1031** [HKUST-Aerial-Robotics/ublox_driver#13]
When I use my own ublox f9p, I can only get the topic /ublox_driver/receiver_lla.
The other topics all give the same errors, as these pictures shown:
![2023-04-26 17-45-45屏幕截图](https://user-images.githubusercontent.com/56681199/234567049-4ac7dac8-750c-44db-819e-72591a8624ec.png)

![2023-04-26 17-46-05屏幕截图](https://user-images.githubusercontent.com/56681199/234567085-1d0272bc-20a6-4e7f-acca-773470796447.png)

I wonder what's the problem.
BTW,  I have already used the provided config file  ucenter_config_f9p_gvins.txt, however, it does not work.

**Comment by yyyxs1125** [comment]
Just source ./devel/setup.bash in each terminal, the problem will be solved.
