### ISSUE TITLE
Cannot locate node of type [ublox_driver] in package [ublox_driver]

### ISSUE THREAD

**Issue by kylinbaozi** [HKUST-Aerial-Robotics/ublox_driver#14]
![image](https://github.com/HKUST-Aerial-Robotics/ublox_driver/assets/44959319/8594c5f1-b822-45da-9ba2-43d717cee73e)

I'm sorry, I'm a novice and I encountered this problem. Could you please answer it

**Comment by kylinbaozi** [comment]
i used banana pi m2-zero,armbian22

**Comment by git-zhang-5665** [comment]
I encountered the same problem, how did you solve it?

**Comment by shaozu** [comment]
Hi, @kylinbaozi @git-zhang-5665. You may need to set the proper environment variables by `source devel/setup.bash` command.
