### ISSUE TITLE
Cannot rostopic echo time_pulse_info

### ISSUE THREAD

**Issue by Erika1kuta** [HKUST-Aerial-Robotics/ublox_driver#15]
Thanks for your contribution, it is easier to use than the official driver. My problem is I can't receive topic about time_pulse_info, and strangely, I can receive other topic at the same time. Looking forward to your help. Thanks.

**Comment by Erika1kuta** [comment]
I use your configuration file, but ublox f9p I use is evaluation kit that just needs to connect to my device using type-c, I am wondering if this cause pulse cannot be input correctly.

**Comment by Erika1kuta** [comment]
Sorry, I should open the

**Comment by shaozu** [comment]
Hi, @Erika1kuta. Sorry for the late reply. The topic `time_pulse_info` is not published by `ublox_driver` itself but another sensor board when it is triggered by the receiver's PPS signal. This topic is used for time synchronization only.
