### ISSUE TITLE
Are /ublox_driver/receiver_lla and /ublox_driver/receiver_pvt the same under RTK?

### ISSUE THREAD

**Issue by yyyxs1125** [HKUST-Aerial-Robotics/ublox_driver#17]
Hi everyone,

I can capture RTK solution by using a ZED f9p but I don't know is there any difference between /ublox_driver/receiver_lla and /ublox_driver/receiver_pvt in terms of langtitude, latitude and altitude. Are they the same or  /ublox_driver/receiver_lla is the original GNSS data and /ublox_driver/receiver_pvt is the corrected data by Ntrip.

Many thanks!

**Comment by shaozu** [comment]
Hi, @yyyxs1125. They are exactly the same in terms of latitude, longitude and altitude. Both are corrected solution but `/ublox_driver/receiver_pvt` gives you more information like velocity and solution's type.
