### ISSUE TITLE
curr_time.time is always equal to 0

### ISSUE THREAD

**Issue by firefly-hub** [HKUST-Aerial-Robotics/ublox_driver#18]
@shaozu When msg_type is UBX_NAVPOS_ID, the current time curr_time.time is always equal to 0. Is this a problem with the code?

**Comment by shaozu** [comment]
@firefly-hub Did you check the GNSS signal in your test environment? i.e., if there is no GNSS/weak GNSS, the time will be 0.

**Comment by zhh2005757** [comment]
> @shaozu When msg_type is UBX_NAVPOS_ID, the current time curr_time.time is always equal to 0. Is this a problem with the code?

I think the code need your current system time to calculate gps week, so I add such a line of code to give curr_time a value and it works
`curr_time = sec2time(ros::Time::now().toSec());`
