### ISSUE TITLE
About Galileo!  Why do we need to reverse the bytes in each word when building a buffer?

### ISSUE THREAD

**Issue by Steph00L** [HKUST-Aerial-Robotics/ublox_driver#19]
Hi! I have a confusion in "UbloxMessageProcessor::decode_GAL_subframe".
Why do we need to reverse the bytes in each word like this,
`    for (i=k=0;i<8;i++,p+=4) 
        for (j=0;j<4;j++) 
            buff[k++]=p[3-j];`

**Comment by shaozu** [comment]
Hi, @Steph00L. This is because UBX-RXM-SFRBX stores the actual ephemeris data in unsigned little-endian 32-bit integer, as specified in Table.3.16.6.1 (page 155) of [UBX-18010854 - R08](https://www.mouser.com/pdfDocs/u-blox_ZED-F9P-04B_ID.pdf).
