### ISSUE TITLE
No ephm output. Any example config available?

### ISSUE THREAD

**Issue by BRNKR** [HKUST-Aerial-Robotics/ublox_driver#2]
Hey,

we are trying to get your GVINS package running. For this we want to use your Ublox driver. Unfortunately we don't get any messages from the topic ephm. We have enabled GPS, SBAS and Galileo here in Europe. Also the messages UBX-RXM-RAWX, UBX-RXM-SFRBX and UBX-NAV-PVT are set to be published.

Can you maybe provide more info about your config or upload an example config? thank you!

**Comment by shaozu** [comment]
Hi, @TobiMiller, I have just uploaded the receiver's config at *config/ucenter_config_f9p_gvins.txt*. 

Hope it helps.

**Comment by BRNKR** [comment]
Thank you a lot! Will give it a try :)

**Comment by BRNKR** [comment]
ok that fixed it.
