### ISSUE TITLE
Is there a bug in "decode_GPS_subframe"?

### ISSUE THREAD

**Issue by Steph00L** [HKUST-Aerial-Robotics/ublox_driver#20]
I notice that when "Set bits to subframe buffer",
`subfrm[ephem->sat]` is used instead of `subfrm[ephem->sat - 1]`.
 I also observed that 'subfrm[ephem->sat - 1]' is used in other systems(Galileo,BeiDou,GLONASS). 
 Could this be an indexing error?
Thanks~

**Comment by shaozu** [comment]
Hi, @Steph00L. Indeed it's an indexing error. The bug has been fixed and thanks for pointing this out!
