### ISSUE TITLE
ublox_message_processor prints errors

### ISSUE THREAD

**Issue by BRNKR** [HKUST-Aerial-Robotics/ublox_driver#3]
Hey,

after flashing the provided config i get following prints from the node. Everything right?

```
E0630 15:30:10.012120 26483 ublox_message_processor.cpp:305] ubx rxmrawx week=0 error
E0630 15:31:45.277527 26483 ublox_message_processor.cpp:787] decode_bds_d1 error: frn=0 0 3
E0630 15:32:14.297196 26483 ublox_message_processor.cpp:787] decode_bds_d1 error: frn=1 0 3
```

**Comment by shaozu** [comment]
If it just happens at beginning, it normal since the code detected a cross-frame ephemeris.

**Comment by BRNKR** [comment]
sorry no :( it is continuous

**Comment by shaozu** [comment]
Then maybe unstable Beidou tracking in your region. BTW the ephemeris error for Galileo is fine because I only handled one types of its ephemeris.

**Comment by BRNKR** [comment]
Is Beidou necessary for your code?

**Comment by shaozu** [comment]
No, any combination of satellite system is ok.
