### ISSUE TITLE
Bad accuracy with NTRIP data

### ISSUE THREAD

**Issue by BRNKR** [HKUST-Aerial-Robotics/ublox_driver#4]
Hey,

i am feeding the rtcm messages from my german ntrip provider over udp to your node. i am using "str2str" from the RTKLib. The gps position is drifting a lot. 

i dont have this problem with https://github.com/ros-agriculture/ublox_f9p and https://github.com/ros-agriculture/ntrip_ros.

any idea what i am doing wrong? Is str2str not providing the correct data for you?

Thank you!

**Comment by shaozu** [comment]
I suggest you to check the `diff_soln` and `carr_soln` flags in published `GnssPVTSolnMsg`. [Here](https://github.com/HKUST-Aerial-Robotics/gnss_comm/blob/main/msg/GnssPVTSolnMsg.msg) is the definition of this message type.

**Comment by BRNKR** [comment]
will check that out. on other drivers this info is in NavSatStatus Message included, which i observed.
