### ISSUE TITLE
issue while launching

### ISSUE THREAD

**Issue by dineshrboson** [HKUST-Aerial-Robotics/ublox_driver#5]
![Screenshot from 2021-09-09 15-46-17](https://user-images.githubusercontent.com/77951479/132668450-0c28d910-6b37-4f48-80e1-c351c76c9005.png)

I didnot understood what changes must be made in u-centre 2
I just connected my ublocks zed f9p to my linux laptop and tried to launch it didnot worked
so i put to default and tried launching

**Comment by shaozu** [comment]
Hi, @dineshrboson. Firstly the [ublox config file](https://github.com/HKUST-Aerial-Robotics/ublox_driver/blob/main/config/ucenter_config_f9p_gvins.txt) in our repo is not readable and you just need to load that to your F9P via u-center.

For the error message I guess you set the `online` parameter to 0 so the driver thought you want to process the recorded data as specified by `ubx_filepath`, which does not exist in your PC.

**Comment by dineshrboson** [comment]
![Screenshot from 2021-09-13 11-48-39](https://user-images.githubusercontent.com/77951479/133033417-bb71d0cc-96b2-4818-a7c9-11f62f9617f3.png)
![Screenshot from 2021-09-13 11-48-48](https://user-images.githubusercontent.com/77951479/133033426-8ed573ef-2243-47e5-8143-03fe0df78d58.png)
![Screenshot from 2021-09-13 11-48-59](https://user-images.githubusercontent.com/77951479/133033429-90c738c9-a561-4ce7-b4ee-13b81bd26d29.png)

**Comment by dineshrboson** [comment]
Downloaded ucentre for windows connected gps module and next tools -> receiver configuration -> loaded your config file and 
removed gps and connected to linux

**Comment by dineshrboson** [comment]
Tried to do launch file the same error is being shown and I checked yaml file its showing 1 is for serial port and 0 is for file. I kept it as 1

**Comment by dineshrboson** [comment]
ls dev/ttyACM* is showing dev/ttyACM0

**Comment by shaozu** [comment]
Hi, @dineshrboson. Thanks for the info. I have updated the code to address this issue.

**Comment by shaozu** [comment]
BTW the old code should work normally even with that error message.

**Comment by dineshrboson** [comment]
Thanks for the reply 
I tried relaunching after pulling the latest code and I found that it's working fine but there is no data on the topic.
If you have some time can you please explain this thing
I have ublox z9fp base and rover and I am looking for cm level accuracy can you guide me the exact steps to be followed.
And also I want that information in topics with high hz rate.

**Comment by shaozu** [comment]
Did you grant your account the permission on serial r/w? if not, try `sudo usermod -aG dialout $USER`.

**Comment by dineshrboson** [comment]
Steps that I did 
1)  connected ublox zed_fp9 to windows laptop and downloaded your txt file and updated my firmware to 1.13 and flashed from tools in the menu.
2) Now I need some info after this step , so do I need to remove the GPS module and connect to my Linux machine and launch the file? that's what I did even after checking ttyACM0 and by doing sudo chmod that port but no info is being coming on the topic

**Comment by dineshrboson** [comment]
![IMG_20210914_230802(1)](https://user-images.githubusercontent.com/77951479/133313053-40882304-65ef-4c18-84ef-3467039e2100.jpg)

**Comment by dineshrboson** [comment]
And in my ucentre screen it looks like 3D/GNSSD
So I believe it became grownd station and now I need to connect xbee and receiver to my Linux laptop and launch the file so that I'll get data

**Comment by dineshrboson** [comment]
My question is your package is compatible for only one ublox zed f9ps or we can use both base station and rover at the same time

**Comment by dineshrboson** [comment]
Hey I made it working I saved the conf after loading your conf file and now I am getting data on the topic thanks close the issue when you see it

**Comment by shaozu** [comment]
Glad to hear that and good luck to your project!
