### ISSUE TITLE
help to obtain rtk solution

### ISSUE THREAD

**Issue by dineshrboson** [HKUST-Aerial-Robotics/ublox_driver#6]
If your receiver owns an internal RTK engine (for example, ZED-F9P), you can input RTCM messages from the GNSS base station to the receiver in order to obtain the cm-level accurate RTK localization result. Our software can forward the RTCM stream from a local socket to the receiver's serial port. Nowadays many GNSS stations distribute their RTCM streams via NTRIP protocol and you can easily fetch the NTRIP data and map it to a local socket via RTKLIB. Following those commands to build RTKLIB and setup the RTCM stream:

I connected my zed f9ps base station to the ucentre, flashed 1.13 firmware and loaded base conf to it and in the tools->ntrip client-> I added one ip port and uname and password and selected mount point and clicked ok 
then I executed 
./str2str -in ntrip://${NTRIP_SITE}:${NTRIP_PORT}/${MOUNT_POINT} -out tcpsvr://:3503
by changing all ntrip site and remaining respectively.
and its keep on telling 401 unauthorized and I dont know where to enter uname and pw
so thats 1st case and 2nd case is
rtk2go.com
2101 port
it does not ask for uname and password so I selected mount and configured ntrip client in ucentre
so this time when I executed 
./str2str -in ntrip://${NTRIP_SITE}:${NTRIP_PORT}/${MOUNT_POINT} -out tcpsvr://:3503
with ./str2str -in ntrip://$rtk2gocom:2101/ACACU -out tcpsvr://:3503
This time its showing bytespersecond and but the end its showing (2)waiting
when I changed the yaml file to 1 in input_rtcm its saying you cannot connect to port 3503

**Comment by shaozu** [comment]
According to the manual of RTKLIB, the ntrip client parameter for `str2str` is `ntrip://[user[:passwd]@]addr[:port][/mntpnt]`.

In our experiment we use the public GNSS reference station maintained by the government as base station and no username and password are required. So I never connected two F9Ps together for a RTK setup. However this setup is very common and is certainly doable. `rtk2go.com` is one way to publish data in ntrip protocol, and I think `str2str` also has similar function. In you first step I suggest you to connect two receivers on a single linux PC and try to use `str2str` to stream the serial data from base station to the rover in ntrip protocol. You can type `str2str -h` to check all data mapping functions of RTKLIB.

**Comment by dineshrboson** [comment]
Hi is there any topic publishing heading from your ublox package.

**Comment by shaozu** [comment]
No. But you can get one easily from the north and east component of the velocity vector in [GnssPVTSolnMsg](https://github.com/HKUST-Aerial-Robotics/gnss_comm/blob/a2035fec1cc427bba184d25ff1fde8dcf23c9ce1/msg/GnssPVTSolnMsg.msg#L19).
