### ISSUE TITLE
'Not received enough bytes ~' problem

### ISSUE THREAD

**Issue by JuyeopHan** [HKUST-Aerial-Robotics/ublox_driver#7]
Hi!

I guess i solved that problem. << I tried to launch 'ublox_driver.launch', but I got an error with the messages "Not received enough bytes: .... while expect ...".
I think the problem might be related to the messages, but i couldn't know how can i fix it.

but I still have an issue that i couldn't get a topic "/ublox_driver/time_pulse_info".  When i execute the launch file, the terminal gives the error message like "E1105 12:31:57.385229  7462 ublox_message_processor.cpp:823] ubx rxmsfrbx length error: sat=E08 len=48". Is that error related to the issue i have?
![Screenshot from 2021-11-05 12-32-05](https://user-images.githubusercontent.com/82950730/140454077-3880c2f2-f6bc-42e7-8365-592872b7ae40.png)

**Comment by shaozu** [comment]
Hi, @JuyeopHan. The error messages in the picture is normal. The reason is that there are two types of ephemeris data for Galileo satellites but we only parse one of them. The ephemeris information is still complete and good to use.

As for the `/ublox_driver/time_pulse_info`, you may check your receiver's config on the pulse setting with u-center. If you use ublox F9P, you can try our config to see if it can solve your problem. Let me know if it is still not working.

And for your previous question related to `Not received enough bytes: .... while expect ...`, you can also post your solution if you don't mind, as this may also help others with the same problem.

**Comment by JuyeopHan** [comment]
dear @shaozu,

I've loaded your config file 'ucenter_config_f9p_gvins.txt' through u-center, but it didn't work. Since I'm a newbie for using u-blox F9P, i have no idea of what to change in the pulse setting. Would you mind letting me know?

Also, the problem about Not received enough bytes: .... while expect ... was solved after iI make my receiver output UBX-RXM-RAWX, UBX-RXM-SFRBX and UBX-NAV-PVT.

**Comment by shaozu** [comment]
Hi, @JuyeopHan. If you flash the config we provided, normally the time pulse, as well as the UBX-RXM-RAWX stuff, should be all set. So I suggest you to first check whether the receiver really get flashed with the config file or not. You may also place the receiver on an open outdoor environment to see if the pulse message will come out.

Of course you can also set those time pulse flags manually. A very detailed guide can be found in section 3.11 of the [ZED-F9P integration manual](https://www.u-blox.com/sites/default/files/ZED-F9P_IntegrationManual_UBX-18010802.pdf).

**Comment by JuyeopHan** [comment]
I figured the issue. As you told me, I didn't load the configuration file in the right way.

when the configuration file is loaded, 'stored configuration into BBR/Flash' must be ticked.
Then move to View > Configuration View > CFG(Configuration), and 
![config](https://user-images.githubusercontent.com/82950730/140747929-258fa8c4-22df-4f94-b736-d4264bdbbac4.png)
let the settings as shown above, and send these settings.

Thank you!

**Comment by shaozu** [comment]
You're welcome! I will close this issue now but feel free to reopen it if you have further questions.

**Comment by Erika1kuta** [comment]
> I figured the issue. As you told me, I didn't load the configuration file in the right way.
> 
> when the configuration file is loaded, 'stored configuration into BBR/Flash' must be ticked. Then move to View > Configuration View > CFG(Configuration), and ![config](https://user-images.githubusercontent.com/82950730/140747929-258fa8c4-22df-4f94-b736-d4264bdbbac4.png) let the settings as shown above, and send these settings.
> 
> Thank you!

Excuse me, could you receive time_pulse_info now? I can receive other topic except for this. Thank you.
