### ISSUE TITLE
Can the driver take UBX-RXM-RAWX, UBX-RXM-SFRBX and UBX-NAV-PVT raw data and publish the correct msgs?

### ISSUE THREAD

**Issue by maghauke** [HKUST-Aerial-Robotics/ublox_driver#8]
Hi, 

I have collected UBX-RXM-RAWX, UBX-RXM-SFRBX and UBX-NAV-PVT raw data in a rosbag and want the ublox_driver to take this in and publish the desired msgs. Is this possible or is the best to translate the rosbag with these to a .ubx file? What format does such a file follow? Could you provide an example file?

Or is there a better way of solving this?

**Comment by shaozu** [comment]
Hi, @maghauke. You may concate the byte stream from the rosbag (data field only) and save it to a ubx file.
